### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by rootwork** [fdalvi/video-screencaps#1]
Hi! Tried to leave this as a comment on your blog, but not sure if it got through (the confirmation page was just some JSON).

---

Thanks for this! I wanted to let you know I created a new iteration of it to address some of my pain points. Features:

- create an arbitrary number of screencaps
- choose whether or not to create the overall "index" image of screencaps, and whether to remove the individual images
- with no arguments, take just one screencap from the middle of the video, which is nice for quick one-off thumbnailing
- automatically detect the width and height of the video and adjust screencaps in the index accordingly

You can find it at https://github.com/rootwork/bash-scripts/blob/main/videos/vidcap.sh -- much of the top is just setup; the real updated script starts at [line 207](https://github.com/rootwork/bash-scripts/blob/main/videos/vidcap.sh#L207)

**Comment by fdalvi** [comment]
Hi @rootwork,

Your comment is now visible on the blog! This is a very nice improvement, thanks for bringing it to my attention. I've also updated the README so people who come looking can find your script better (5acc72b).

Best,
Fahim
